sudo: required
services:
  - docker

before_install:
  - docker build -t zakaria06/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zakaria06/react-test npm test

after_success:
  - docker build -t zakaria06/multi-client ./client
  - docker build -t zakaria06/multi-nginx ./nginx
  - docker build -t zakaria06/multi-server ./server
  - docker build -t zakaria06/multi-worker ./worker
  
