sudo: required
services:
  - docker

before_install:
  - docker build -t zakaria06/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zakaria06/react-test npm test

after_success:
  - docker build -t zakaria06/multi-client ./client
  - docker build -t zakaria06/multi-nginx ./nginx
  - docker build -t zakaria06/multi-server ./server
  - docker build -t zakaria06/multi-worker ./worker
  
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
#Take those images and push the to Dockerhub
  - docker push zakaria06/multi-client
  - docker push zakaria06/multi-nginx
  - docker push zakaria06/multi-server
  - docker push zakaria06/multi-worker
 
